import Slider from '@mui/material/Slider';

export const allusers = [

  {
    Id: 1,
    Avatar: "avatar.svg",
    name: "Alice Smith",
    subName: "@alicesmith",
    paymentType: "visa.svg",
    accountNumber: "Ends in ****_**18",
    category: {
       categ1: "Arts",
       categ2: "Business",
       categ3: "Travel",
    },
    percentageValue: "40%",
    Slider: "Slider.png",
  },
  {
    Id: 2,
    Avatar: "avatar2.svg",
    name: "Bob JohnSon",
    subName: "@bobjohnson",
    paymentType: "mastercard.svg",
    accountNumber: "Ends in ****_**98",
    category: {
       categ1: "Books",
       categ2: "Computers",
    },
    percentageValue: "10%",
    Slider: "Slider.png",
  },
  {
    Id: 3,
    Avatar: "avatar1.svg",
    name: "Clara Garcia",
    subName: "@claragarcia",
    paymentType: "visa.svg",
    accountNumber: "Ends in ****_**85",
    category: {
       categ1: "Kitchen",
       categ2: "Books",
    },
    percentageValue: "80%",
    Slider: "Slider.png",
  },
  {
    Id: 4,
    Avatar: "avatar1.svg",
    name: "Emma Lee",
    subName: "@emmalee",
    paymentType: "mastercard.svg",
    accountNumber: "Ends in ****_**76",
    category: {
       categ1: "Furniture",
    },
    percentageValue: "40%",
    Slider: "Slider.png",
  },
  {
    Id: 5,
    Avatar: "avatar3.svg",
    name: "Grace Taylor",
    subName: "@gracetaylor",
    paymentType: "visa.svg",
    accountNumber: "Ends in ****_**71",
    category: {
       categ1: "Beauty",
       categ2: "Apparal",
       categ3: "Sale"
    },
    percentageValue: "60%",
    Slider: "Slider.png",
  },
  {
    Id: 6,
    Avatar: "avatar.svg",
    name: "Isaballa Clerk",
    subName: "@isaballaclerk",
    paymentType: "mastercard.svg",
    accountNumber: "Ends in ****_**99",
    category: {
       categ1: "AI",
       categ2: "Machine Learning",
    },
    percentageValue: "20%",
    Slider: "Slider.png",
  },
  {
    Id: 7,
    Avatar: "avatar2.svg",
    name: "David Brown",
    subName: "@davidbrown",
    paymentType: "visa.svg",
    accountNumber: "Ends in ****_**65",
    category: {
       categ1: "Lazy",
       categ2: "Music",
       categ3: "Movie",
    },
    percentageValue: "40%",
    Slider: "Slider.png",
  },
  {
    Id: 8,
    Avatar: "avatar3.svg",
    name: "Frank Wong",
    subName: "@frankwong",
    paymentType: "mastercard.svg",
    accountNumber: "Ends in ****_**56",
    category: {
       categ1: "Sports",
       categ2: "Jogging",
    },
    percentageValue: "20%",
    Slider: "Slider.png",
  },
  {
    Id: 9,
    Avatar: "avatar.svg",
    name: "Isaballa Clerk",
    subName: "@isaballaclerk",
    paymentType: "visa.svg",
    accountNumber: "Ends in ****_**92",
    category: {
       categ1: "Beauty",
       categ2: "Apparal",
       categ3: "Sale",
    },
    percentageValue: "60%",
    Slider: "Slider.png",
  },
  {
    Id: 10,
    Avatar: "avatar2.svg",
    name: "David Brown",
    subName: "@davidbrown",
    paymentType: "mastercard.svg",
    accountNumber: "Ends in ****_**42",
    category: {
       categ1: "Sports",
       categ2: "Jogging",
    },
    percentageValue: "20%",
    Slider: "Slider.png",
  },

];
