export const allusers = [

  {
    Id: 1,
    name: "Alice Smith",
    subName: "@alicesmith",
    paymentType: "visa.svg",
    category: "Arts",
    percentageValue: "40%",
  },
  {
    Id: 2,
    name: "Bob JohnSon",
    subName: "@bobjohnson",
    paymentType: "mastercard.svg",
    category: "Computers",
    percentageValue: "70%",
  },
  {
    Id: 3,
    name: "Clara Garcia",
    subName: "@claragarcia",
    paymentType: "visa.svg",
    category: "Kitchen",
    percentageValue: "90%",
  },
  {
    Id: 4,
    name: "Emma Lee",
    subName: "@emmalee",
    paymentType: "mastercard.svg",
    category: "Furniture",
    percentageValue: "30%",
  },
  {
    Id: 5,
    name: "Grace Taylor",
    subName: "@gracetaylor",
    paymentType: "visa.svg",
    category: "Beauty",
    percentageValue: "40%",
  },
  {
    Id: 6,
    name: "Isaballa Clerk",
    subName: "@isaballaclerk",
    paymentType: "mastercard.svg",
    category: "Machine Learning",
    percentageValue: "20%",
  },
  {
    Id: 7,
    name: "David Brown",
    subName: "@davidbrown",
    paymentType: "visa.svg",
    category: "Music",
    percentageValue: "100%",
  },
  {
    Id: 8,
    name: "Frank Wong",
    subName: "@frankwong",
    paymentType: "mastercard.svg",
    category: "Sports",
    percentageValue: "30%",
  },
  {
    Id: 9,
    name: "Isaballa Clerk",
    subName: "@isaballaclerk",
    paymentType: "visa.svg",
    category: "Apparal",
    percentageValue: "45%",
  },
  {
    Id: 10,
    name: "David Brown",
    subName: "@davidbrown",
    paymentType: "mastercard.svg",
    category: "Jogging",
    percentageValue: "55%",
  },

];
